apiVersion: v1
data:
  licensekey: {{ .Values.app.newrelic.key }}
  redisauth: {{ .Values.redis.auth }}
kind: Secret
metadata:
  name: {{ .Values.app.secret }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca
data:
  server-ca.pem: {{ .Values.redis.tlsca }}
