app:
  replicas: 1
  port: 8080
  newrelic:
    key: bmV3cmVsaWMta2V5Cg==
  configmap: bloom-filter-cm
  secret: bloom-filter-secret

service:
  port: 8080

image:
  repository: ashbourne1990/node-bloom-filter-service
  tag: latest

env: production

redis:
  port: 6378
  ca:
    name: server-ca.pem
    path: /ssl-certs
